rsna
[RSNADataset] Scanning files...
[RSNADataset] Found 1000 already processed bags
[RSNADataset] Number of bags found: 1000
rsna
[RSNADataset] Scanning files...
[RSNADataset] Found 150 already processed bags
[RSNADataset] Number of bags found: 150
Epoch 1/1, Train Loss: 0.6685, Train Accuracy: 0.6175, Val Loss: 0.6404, Val Accuracy: 0.6100
Final model saved to ./models/rsna/model_final.pth
/home/javitrucas/TFG/scripts/medical_scripts/medical_evaluation.py:17: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model = torch.load(self.model_path, map_location=self.device)
Traceback (most recent call last):
  File "/home/javitrucas/TFG/scripts/medical_scripts/medical_evaluation.py", line 18, in _load_model
    model.to(self.device)  # Mover el modelo al dispositivo adecuado
    ^^^^^^^^
AttributeError: 'collections.OrderedDict' object has no attribute 'to'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/javitrucas/TFG/scripts/medical_scripts/medical_main.py", line 75, in <module>
    evaluator.evaluate()
  File "/home/javitrucas/TFG/scripts/medical_scripts/medical_evaluation.py", line 29, in evaluate
    model = self._load_model()  # Cargar el modelo
            ^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/TFG/scripts/medical_scripts/medical_evaluation.py", line 23, in _load_model
    raise RuntimeError(f"Error loading model from {self.model_path}: {e}")
RuntimeError: Error loading model from ./models/rsna/model.pth: 'collections.OrderedDict' object has no attribute 'to'
