rsna
[RSNADataset] Scanning files...
[RSNADataset] Found 1000 already processed bags
[RSNADataset] Number of bags found: 1000
rsna
[RSNADataset] Scanning files...
[RSNADataset] Found 150 already processed bags
[RSNADataset] Number of bags found: 150
Epoch 1/10, Train Loss: 0.6648, Train Accuracy: 0.6088, Val Loss: 0.6405, Val Accuracy: 0.6300
Final model saved to ./models/rsna/model_final.pth
Epoch 2/10, Train Loss: 0.5655, Train Accuracy: 0.7075, Val Loss: 0.5736, Val Accuracy: 0.6800
Final model saved to ./models/rsna/model_final.pth
Epoch 3/10, Train Loss: 0.5410, Train Accuracy: 0.7275, Val Loss: 0.5575, Val Accuracy: 0.7100
Final model saved to ./models/rsna/model_final.pth
Epoch 4/10, Train Loss: 0.5435, Train Accuracy: 0.7350, Val Loss: 0.5249, Val Accuracy: 0.7450
Final model saved to ./models/rsna/model_final.pth
Epoch 5/10, Train Loss: 0.5116, Train Accuracy: 0.7438, Val Loss: 0.5886, Val Accuracy: 0.6900
Final model saved to ./models/rsna/model_final.pth
Epoch 6/10, Train Loss: 0.4882, Train Accuracy: 0.7625, Val Loss: 0.5155, Val Accuracy: 0.7550
Final model saved to ./models/rsna/model_final.pth
Epoch 7/10, Train Loss: 0.4998, Train Accuracy: 0.7662, Val Loss: 0.5484, Val Accuracy: 0.7100
Final model saved to ./models/rsna/model_final.pth
Epoch 8/10, Train Loss: 0.4899, Train Accuracy: 0.7725, Val Loss: 0.4983, Val Accuracy: 0.7750
Final model saved to ./models/rsna/model_final.pth
Epoch 9/10, Train Loss: 0.4726, Train Accuracy: 0.7750, Val Loss: 0.6836, Val Accuracy: 0.6600
Final model saved to ./models/rsna/model_final.pth
Epoch 10/10, Train Loss: 0.4656, Train Accuracy: 0.7800, Val Loss: 0.5010, Val Accuracy: 0.7550
Final model saved to ./models/rsna/model_final.pth
Traceback (most recent call last):
  File "/home/javitrucas/TFG/scripts/medical_scripts/medical_evaluation.py", line 76, in _load_model
    model = MILModel(feature_dim=512).to(self.device)
            ^^^^^^^^
NameError: name 'MILModel' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/javitrucas/TFG/scripts/medical_scripts/medical_main.py", line 75, in <module>
    evaluator.evaluate()
  File "/home/javitrucas/TFG/scripts/medical_scripts/medical_evaluation.py", line 40, in evaluate
    model = self._load_model()
            ^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/TFG/scripts/medical_scripts/medical_evaluation.py", line 81, in _load_model
    raise RuntimeError(f"Error loading model: {e}")
RuntimeError: Error loading model: name 'MILModel' is not defined
