2025-04-18 13:29:10,179 INFO    MainThread:1757280 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-04-18 13:29:10,179 INFO    MainThread:1757280 [wandb_setup.py:_flush():67] Configure stats pid to 1757280
2025-04-18 13:29:10,179 INFO    MainThread:1757280 [wandb_setup.py:_flush():67] Loading settings from /home/javitrucas/.config/wandb/settings
2025-04-18 13:29:10,180 INFO    MainThread:1757280 [wandb_setup.py:_flush():67] Loading settings from /home/javitrucas/TFG/notebooks/wandb/settings
2025-04-18 13:29:10,180 INFO    MainThread:1757280 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-04-18 13:29:10,180 INFO    MainThread:1757280 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250418_132910-jn4c5ghi/logs/debug.log
2025-04-18 13:29:10,180 INFO    MainThread:1757280 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250418_132910-jn4c5ghi/logs/debug-internal.log
2025-04-18 13:29:10,180 INFO    MainThread:1757280 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7faa85812a10>
2025-04-18 13:29:10,181 INFO    MainThread:1757280 [wandb_init.py:init():761] calling init triggers
2025-04-18 13:29:10,181 INFO    MainThread:1757280 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'dataset_name': 'rsna-features_resnet18', 'input_feature_dim': 512, 'feature_dim': 64, 'pooling_type': 'attention', 'num_epochs': 50, 'learning_rate': 0.001, 'batch_size': 1, 'val_prop': 0.2, 'seed': 0, 'use_inst_distances': False, 'adj_mat_mode': 'relative', '_wandb': {}}
2025-04-18 13:29:10,181 INFO    MainThread:1757280 [wandb_init.py:init():784] starting backend
2025-04-18 13:29:10,181 INFO    MainThread:1757280 [wandb_init.py:init():788] sending inform_init request
2025-04-18 13:29:10,219 INFO    MainThread:1757280 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-18 13:29:10,220 INFO    MainThread:1757280 [wandb_init.py:init():803] backend started and connected
2025-04-18 13:29:10,224 INFO    MainThread:1757280 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-04-18 13:29:10,225 INFO    MainThread:1757280 [wandb_init.py:init():896] updated telemetry
2025-04-18 13:29:10,236 INFO    MainThread:1757280 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-04-18 13:29:10,773 INFO    MainThread:1757280 [wandb_init.py:init():995] starting run threads in backend
2025-04-18 13:29:11,006 INFO    MainThread:1757280 [wandb_run.py:_console_start():2377] atexit reg
2025-04-18 13:29:11,006 INFO    MainThread:1757280 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-04-18 13:29:11,007 INFO    MainThread:1757280 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-04-18 13:29:11,007 INFO    MainThread:1757280 [wandb_run.py:_redirect():2317] Redirects installed.
2025-04-18 13:29:11,011 INFO    MainThread:1757280 [wandb_init.py:init():1037] run started, returning control to user process
2025-04-18 13:29:49,056 WARNING MsgRouterThr:1757280 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-04-18 13:29:49,059 INFO    MsgRouterThr:1757280 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
2025-04-18 13:29:50,495 INFO    MainThread:1757280 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-04-18 13:29:50,495 INFO    MainThread:1757280 [wandb_init.py:_pause_backend():564] pausing backend
