2025-05-23 12:15:34,614 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121534-d1rtwos7/logs/debug.log
2025-05-23 12:15:34,621 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121534-d1rtwos7/logs/debug-internal.log
2025-05-23 12:15:34,627 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:34,634 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 15, 'num_epochs': 15, 'learning_rate': 0.0001, 'pooling_type': 'attention', 'seed': 1, '_wandb': {}}
2025-05-23 12:15:34,640 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:34,647 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:34,676 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121534-8wpej3wh/logs/debug.log
2025-05-23 12:15:34,682 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121534-8wpej3wh/logs/debug-internal.log
2025-05-23 12:15:34,689 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:34,697 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 15, 'num_epochs': 15, 'learning_rate': 0.0001, 'pooling_type': 'attention', 'seed': 2, '_wandb': {}}
2025-05-23 12:15:34,705 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:34,711 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:34,738 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121534-e6nqsis6/logs/debug.log
2025-05-23 12:15:34,748 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121534-e6nqsis6/logs/debug-internal.log
2025-05-23 12:15:34,755 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:34,761 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 15, 'num_epochs': 15, 'learning_rate': 0.0001, 'pooling_type': 'attention', 'seed': 3, '_wandb': {}}
2025-05-23 12:15:34,768 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:34,774 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:34,803 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121534-0gsg89ll/logs/debug.log
2025-05-23 12:15:34,811 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121534-0gsg89ll/logs/debug-internal.log
2025-05-23 12:15:34,817 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:34,824 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 15, 'num_epochs': 15, 'learning_rate': 0.0001, 'pooling_type': 'attention', 'seed': 4, '_wandb': {}}
2025-05-23 12:15:34,831 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:34,837 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:34,869 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121534-5dmw7wi6/logs/debug.log
2025-05-23 12:15:34,876 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121534-5dmw7wi6/logs/debug-internal.log
2025-05-23 12:15:34,882 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:34,889 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 15, 'num_epochs': 15, 'learning_rate': 0.0001, 'pooling_type': 'mean', 'seed': 0, '_wandb': {}}
2025-05-23 12:15:34,898 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:34,904 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:34,931 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121534-okvqn23k/logs/debug.log
2025-05-23 12:15:34,937 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121534-okvqn23k/logs/debug-internal.log
2025-05-23 12:15:34,946 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:34,953 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 15, 'num_epochs': 15, 'learning_rate': 0.0001, 'pooling_type': 'mean', 'seed': 1, '_wandb': {}}
2025-05-23 12:15:34,959 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:34,966 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:34,995 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121534-kx2w279x/logs/debug.log
2025-05-23 12:15:35,002 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121534-kx2w279x/logs/debug-internal.log
2025-05-23 12:15:35,009 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:35,015 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 15, 'num_epochs': 15, 'learning_rate': 0.0001, 'pooling_type': 'mean', 'seed': 2, '_wandb': {}}
2025-05-23 12:15:35,022 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:35,028 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:35,057 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121535-4fnlek9t/logs/debug.log
2025-05-23 12:15:35,065 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121535-4fnlek9t/logs/debug-internal.log
2025-05-23 12:15:35,071 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:35,078 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 15, 'num_epochs': 15, 'learning_rate': 0.0001, 'pooling_type': 'mean', 'seed': 3, '_wandb': {}}
2025-05-23 12:15:35,085 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:35,094 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:35,121 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121535-pc5tnmd6/logs/debug.log
2025-05-23 12:15:35,128 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121535-pc5tnmd6/logs/debug-internal.log
2025-05-23 12:15:35,136 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:35,143 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 15, 'num_epochs': 15, 'learning_rate': 0.0001, 'pooling_type': 'mean', 'seed': 4, '_wandb': {}}
2025-05-23 12:15:35,150 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:35,157 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:35,188 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121535-d7qe0qth/logs/debug.log
2025-05-23 12:15:35,194 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121535-d7qe0qth/logs/debug-internal.log
2025-05-23 12:15:35,201 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:35,207 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 15, 'num_epochs': 15, 'learning_rate': 0.0001, 'pooling_type': 'max', 'seed': 0, '_wandb': {}}
2025-05-23 12:15:35,214 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:35,221 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:35,250 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121535-7g64fv61/logs/debug.log
2025-05-23 12:15:35,257 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121535-7g64fv61/logs/debug-internal.log
2025-05-23 12:15:35,264 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:35,271 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 15, 'num_epochs': 15, 'learning_rate': 0.0001, 'pooling_type': 'max', 'seed': 1, '_wandb': {}}
2025-05-23 12:15:35,277 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:35,287 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:35,313 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121535-9rtn51pb/logs/debug.log
2025-05-23 12:15:35,321 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121535-9rtn51pb/logs/debug-internal.log
2025-05-23 12:15:35,329 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:35,337 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 15, 'num_epochs': 15, 'learning_rate': 0.0001, 'pooling_type': 'max', 'seed': 2, '_wandb': {}}
2025-05-23 12:15:35,344 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:35,351 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:35,380 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121535-6i6qw714/logs/debug.log
2025-05-23 12:15:35,387 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121535-6i6qw714/logs/debug-internal.log
2025-05-23 12:15:35,394 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:35,401 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 15, 'num_epochs': 15, 'learning_rate': 0.0001, 'pooling_type': 'max', 'seed': 3, '_wandb': {}}
2025-05-23 12:15:35,407 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:35,414 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:35,443 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121535-kji02g3t/logs/debug.log
2025-05-23 12:15:35,450 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121535-kji02g3t/logs/debug-internal.log
2025-05-23 12:15:35,457 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:35,464 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 15, 'num_epochs': 15, 'learning_rate': 0.0001, 'pooling_type': 'max', 'seed': 4, '_wandb': {}}
2025-05-23 12:15:35,470 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:35,480 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:35,509 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121535-c7e2la4q/logs/debug.log
2025-05-23 12:15:35,516 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121535-c7e2la4q/logs/debug-internal.log
2025-05-23 12:15:35,525 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:35,532 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.01, 'pooling_type': 'attention', 'seed': 0, '_wandb': {}}
2025-05-23 12:15:35,539 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:35,545 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:35,575 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121535-kr5j2365/logs/debug.log
2025-05-23 12:15:35,582 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121535-kr5j2365/logs/debug-internal.log
2025-05-23 12:15:35,589 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:35,596 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.01, 'pooling_type': 'attention', 'seed': 1, '_wandb': {}}
2025-05-23 12:15:35,603 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:35,610 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:35,640 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121535-x3zrnlej/logs/debug.log
2025-05-23 12:15:35,647 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121535-x3zrnlej/logs/debug-internal.log
2025-05-23 12:15:35,654 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:35,661 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.01, 'pooling_type': 'attention', 'seed': 2, '_wandb': {}}
2025-05-23 12:15:35,669 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:35,677 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:35,704 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121535-nqz056ra/logs/debug.log
2025-05-23 12:15:35,711 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121535-nqz056ra/logs/debug-internal.log
2025-05-23 12:15:35,720 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:35,727 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.01, 'pooling_type': 'attention', 'seed': 3, '_wandb': {}}
2025-05-23 12:15:35,734 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:35,740 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:35,770 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121535-hpp3zkl6/logs/debug.log
2025-05-23 12:15:35,777 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121535-hpp3zkl6/logs/debug-internal.log
2025-05-23 12:15:35,784 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:35,791 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.01, 'pooling_type': 'attention', 'seed': 4, '_wandb': {}}
2025-05-23 12:15:35,798 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:35,805 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:35,838 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121535-n4kfneyu/logs/debug.log
2025-05-23 12:15:35,846 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121535-n4kfneyu/logs/debug-internal.log
2025-05-23 12:15:35,853 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:35,860 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.01, 'pooling_type': 'mean', 'seed': 0, '_wandb': {}}
2025-05-23 12:15:35,870 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:35,876 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:35,905 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121535-g7s57ic4/logs/debug.log
2025-05-23 12:15:35,915 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121535-g7s57ic4/logs/debug-internal.log
2025-05-23 12:15:35,922 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:35,929 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.01, 'pooling_type': 'mean', 'seed': 1, '_wandb': {}}
2025-05-23 12:15:35,935 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:35,942 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:35,972 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121535-xxefqnqi/logs/debug.log
2025-05-23 12:15:35,979 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121535-xxefqnqi/logs/debug-internal.log
2025-05-23 12:15:35,986 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:35,993 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.01, 'pooling_type': 'mean', 'seed': 2, '_wandb': {}}
2025-05-23 12:15:36,000 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:36,008 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:36,037 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121536-wvyjq969/logs/debug.log
2025-05-23 12:15:36,044 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121536-wvyjq969/logs/debug-internal.log
2025-05-23 12:15:36,051 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:36,059 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.01, 'pooling_type': 'mean', 'seed': 3, '_wandb': {}}
2025-05-23 12:15:36,067 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:36,074 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:36,102 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121536-120b6g2p/logs/debug.log
2025-05-23 12:15:36,112 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121536-120b6g2p/logs/debug-internal.log
2025-05-23 12:15:36,119 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:36,126 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.01, 'pooling_type': 'mean', 'seed': 4, '_wandb': {}}
2025-05-23 12:15:36,133 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:36,140 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:36,174 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121536-qjjtti4a/logs/debug.log
2025-05-23 12:15:36,181 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121536-qjjtti4a/logs/debug-internal.log
2025-05-23 12:15:36,188 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:36,195 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.01, 'pooling_type': 'max', 'seed': 0, '_wandb': {}}
2025-05-23 12:15:36,203 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:36,212 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:36,239 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121536-qgeeiee2/logs/debug.log
2025-05-23 12:15:36,246 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121536-qgeeiee2/logs/debug-internal.log
2025-05-23 12:15:36,256 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:36,263 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.01, 'pooling_type': 'max', 'seed': 1, '_wandb': {}}
2025-05-23 12:15:36,270 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:36,277 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:36,307 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121536-nt8muq94/logs/debug.log
2025-05-23 12:15:36,314 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121536-nt8muq94/logs/debug-internal.log
2025-05-23 12:15:36,321 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:36,328 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.01, 'pooling_type': 'max', 'seed': 2, '_wandb': {}}
2025-05-23 12:15:36,335 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:36,342 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:36,372 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121536-hffpeu87/logs/debug.log
2025-05-23 12:15:36,380 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121536-hffpeu87/logs/debug-internal.log
2025-05-23 12:15:36,387 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:36,394 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.01, 'pooling_type': 'max', 'seed': 3, '_wandb': {}}
2025-05-23 12:15:36,403 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:36,411 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:36,439 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121536-kieif6yt/logs/debug.log
2025-05-23 12:15:36,447 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121536-kieif6yt/logs/debug-internal.log
2025-05-23 12:15:36,456 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:36,463 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.01, 'pooling_type': 'max', 'seed': 4, '_wandb': {}}
2025-05-23 12:15:36,470 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:36,477 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:36,509 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121536-feilsi3a/logs/debug.log
2025-05-23 12:15:36,516 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121536-feilsi3a/logs/debug-internal.log
2025-05-23 12:15:36,523 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:36,530 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.001, 'pooling_type': 'attention', 'seed': 0, '_wandb': {}}
2025-05-23 12:15:36,537 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:36,545 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:36,575 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121536-39ntvg7m/logs/debug.log
2025-05-23 12:15:36,582 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121536-39ntvg7m/logs/debug-internal.log
2025-05-23 12:15:36,590 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:36,599 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.001, 'pooling_type': 'attention', 'seed': 1, '_wandb': {}}
2025-05-23 12:15:36,606 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:36,614 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:36,643 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121536-94jzw4df/logs/debug.log
2025-05-23 12:15:36,652 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121536-94jzw4df/logs/debug-internal.log
2025-05-23 12:15:36,660 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:36,667 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.001, 'pooling_type': 'attention', 'seed': 2, '_wandb': {}}
2025-05-23 12:15:36,674 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:36,681 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:36,712 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121536-tvhijgsi/logs/debug.log
2025-05-23 12:15:36,719 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121536-tvhijgsi/logs/debug-internal.log
2025-05-23 12:15:36,726 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:36,733 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.001, 'pooling_type': 'attention', 'seed': 3, '_wandb': {}}
2025-05-23 12:15:36,742 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:36,751 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:36,778 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121536-qc5ae7h1/logs/debug.log
2025-05-23 12:15:36,785 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121536-qc5ae7h1/logs/debug-internal.log
2025-05-23 12:15:36,795 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:36,802 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.001, 'pooling_type': 'attention', 'seed': 4, '_wandb': {}}
2025-05-23 12:15:36,810 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:36,817 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:36,850 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121536-xf987c9g/logs/debug.log
2025-05-23 12:15:36,858 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121536-xf987c9g/logs/debug-internal.log
2025-05-23 12:15:36,865 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:36,872 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.001, 'pooling_type': 'mean', 'seed': 0, '_wandb': {}}
2025-05-23 12:15:36,879 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:36,887 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:36,916 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121536-knaac612/logs/debug.log
2025-05-23 12:15:36,924 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121536-knaac612/logs/debug-internal.log
2025-05-23 12:15:36,931 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:36,940 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.001, 'pooling_type': 'mean', 'seed': 1, '_wandb': {}}
2025-05-23 12:15:36,948 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:36,956 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:36,984 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121536-xo45drur/logs/debug.log
2025-05-23 12:15:36,994 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121536-xo45drur/logs/debug-internal.log
2025-05-23 12:15:37,001 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:37,008 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.001, 'pooling_type': 'mean', 'seed': 2, '_wandb': {}}
2025-05-23 12:15:37,016 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:37,023 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:37,054 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121537-rpxp5zz3/logs/debug.log
2025-05-23 12:15:37,062 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121537-rpxp5zz3/logs/debug-internal.log
2025-05-23 12:15:37,069 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:37,076 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.001, 'pooling_type': 'mean', 'seed': 3, '_wandb': {}}
2025-05-23 12:15:37,083 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:37,094 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:37,122 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121537-vs98cw34/logs/debug.log
2025-05-23 12:15:37,129 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121537-vs98cw34/logs/debug-internal.log
2025-05-23 12:15:37,139 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:37,147 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.001, 'pooling_type': 'mean', 'seed': 4, '_wandb': {}}
2025-05-23 12:15:37,154 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:37,162 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:37,193 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121537-ok9qrywz/logs/debug.log
2025-05-23 12:15:37,201 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121537-ok9qrywz/logs/debug-internal.log
2025-05-23 12:15:37,208 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:37,216 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.001, 'pooling_type': 'max', 'seed': 0, '_wandb': {}}
2025-05-23 12:15:37,223 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:37,230 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:37,262 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121537-ddjrk4sv/logs/debug.log
2025-05-23 12:15:37,269 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121537-ddjrk4sv/logs/debug-internal.log
2025-05-23 12:15:37,277 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:37,287 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.001, 'pooling_type': 'max', 'seed': 1, '_wandb': {}}
2025-05-23 12:15:37,294 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:37,302 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:37,329 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121537-rd40kfs7/logs/debug.log
2025-05-23 12:15:37,339 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121537-rd40kfs7/logs/debug-internal.log
2025-05-23 12:15:37,347 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:37,354 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.001, 'pooling_type': 'max', 'seed': 2, '_wandb': {}}
2025-05-23 12:15:37,362 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:37,369 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:37,400 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121537-qoxhemfh/logs/debug.log
2025-05-23 12:15:37,408 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121537-qoxhemfh/logs/debug-internal.log
2025-05-23 12:15:37,415 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:37,422 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.001, 'pooling_type': 'max', 'seed': 3, '_wandb': {}}
2025-05-23 12:15:37,431 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:37,440 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:37,469 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121537-4jaj6icl/logs/debug.log
2025-05-23 12:15:37,476 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121537-4jaj6icl/logs/debug-internal.log
2025-05-23 12:15:37,487 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:37,494 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.001, 'pooling_type': 'max', 'seed': 4, '_wandb': {}}
2025-05-23 12:15:37,502 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:37,509 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:37,542 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121537-7um67fkd/logs/debug.log
2025-05-23 12:15:37,549 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121537-7um67fkd/logs/debug-internal.log
2025-05-23 12:15:37,557 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:37,564 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.0001, 'pooling_type': 'attention', 'seed': 0, '_wandb': {}}
2025-05-23 12:15:37,572 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:37,580 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:37,609 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121537-gaf0qgyz/logs/debug.log
2025-05-23 12:15:37,617 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121537-gaf0qgyz/logs/debug-internal.log
2025-05-23 12:15:37,625 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:37,634 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.0001, 'pooling_type': 'attention', 'seed': 1, '_wandb': {}}
2025-05-23 12:15:37,642 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:37,650 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:37,681 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121537-wjlx95kv/logs/debug.log
2025-05-23 12:15:37,689 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121537-wjlx95kv/logs/debug-internal.log
2025-05-23 12:15:37,697 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:37,704 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.0001, 'pooling_type': 'attention', 'seed': 2, '_wandb': {}}
2025-05-23 12:15:37,712 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:37,719 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:37,750 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121537-o6mvsfwy/logs/debug.log
2025-05-23 12:15:37,757 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121537-o6mvsfwy/logs/debug-internal.log
2025-05-23 12:15:37,765 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:37,774 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.0001, 'pooling_type': 'attention', 'seed': 3, '_wandb': {}}
2025-05-23 12:15:37,783 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:37,790 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:37,820 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121537-a7ww2b60/logs/debug.log
2025-05-23 12:15:37,830 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121537-a7ww2b60/logs/debug-internal.log
2025-05-23 12:15:37,837 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:37,845 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.0001, 'pooling_type': 'attention', 'seed': 4, '_wandb': {}}
2025-05-23 12:15:37,853 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:37,860 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:37,893 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121537-jsarea2k/logs/debug.log
2025-05-23 12:15:37,901 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121537-jsarea2k/logs/debug-internal.log
2025-05-23 12:15:37,909 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:37,916 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.0001, 'pooling_type': 'mean', 'seed': 0, '_wandb': {}}
2025-05-23 12:15:37,926 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:37,934 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:37,962 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121537-f8efnni6/logs/debug.log
2025-05-23 12:15:37,972 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121537-f8efnni6/logs/debug-internal.log
2025-05-23 12:15:37,980 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:37,988 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.0001, 'pooling_type': 'mean', 'seed': 1, '_wandb': {}}
2025-05-23 12:15:37,995 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:38,003 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:38,033 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121538-8otasspo/logs/debug.log
2025-05-23 12:15:38,040 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121538-8otasspo/logs/debug-internal.log
2025-05-23 12:15:38,048 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:38,055 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.0001, 'pooling_type': 'mean', 'seed': 2, '_wandb': {}}
2025-05-23 12:15:38,065 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:38,073 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:38,102 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121538-hje616tg/logs/debug.log
2025-05-23 12:15:38,111 INFO    MainThread:2433171 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250523_121538-hje616tg/logs/debug-internal.log
2025-05-23 12:15:38,120 INFO    MainThread:2433171 [wandb_init.py:init():761] calling init triggers
2025-05-23 12:15:38,128 INFO    MainThread:2433171 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 20, 'num_epochs': 5, 'learning_rate': 0.0001, 'pooling_type': 'mean', 'seed': 3, '_wandb': {}}
2025-05-23 12:15:38,135 INFO    MainThread:2433171 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-23 12:15:38,145 ERROR   MainThread:2433171 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-23 12:15:38,178 WARNING MainThread:2433171 [wandb_init.py:init():1475] interrupted
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1457, in init
    wi.setup_run_log_directory(run_settings)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 647, in setup_run_log_directory
    self._logger.info(f"Logging user logs to {settings.log_user}")
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/logging/__init__.py", line 1489, in info
    self._log(INFO, msg, args, **kwargs)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/logging/__init__.py", line 1634, in _log
    self.handle(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/logging/__init__.py", line 1644, in handle
    self.callHandlers(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/logging/__init__.py", line 1706, in callHandlers
    hdlr.handle(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/logging/__init__.py", line 978, in handle
    self.emit(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/logging/__init__.py", line 1230, in emit
    StreamHandler.emit(self, record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/logging/__init__.py", line 1114, in emit
    self.flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/logging/__init__.py", line 1094, in flush
    self.stream.flush()
KeyboardInterrupt
2025-05-23 12:15:39,007 INFO    MainThread:2433171 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-05-23 12:15:39,015 INFO    MainThread:2433171 [wandb_init.py:_pause_backend():564] pausing backend
