2025-05-28 18:14:07,479 INFO    MainThread:3453794 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250528_181407-pf1fpgsz/logs/debug.log
2025-05-28 18:14:07,479 INFO    MainThread:3453794 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250528_181407-pf1fpgsz/logs/debug-internal.log
2025-05-28 18:14:07,479 INFO    MainThread:3453794 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f4904456990>
2025-05-28 18:14:07,479 INFO    MainThread:3453794 [wandb_init.py:init():761] calling init triggers
2025-05-28 18:14:07,479 INFO    MainThread:3453794 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 10, 'num_epochs': 5, 'learning_rate': 0.001, 'pooling_type': 'mean', '_wandb': {}}
2025-05-28 18:14:07,479 INFO    MainThread:3453794 [wandb_init.py:init():784] starting backend
2025-05-28 18:14:07,479 INFO    MainThread:3453794 [wandb_init.py:init():788] sending inform_init request
2025-05-28 18:14:07,480 INFO    MainThread:3453794 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-05-28 18:14:07,480 INFO    MainThread:3453794 [wandb_init.py:init():803] backend started and connected
2025-05-28 18:14:07,481 INFO    MainThread:3453794 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-05-28 18:14:07,485 INFO    MainThread:3453794 [wandb_init.py:init():896] updated telemetry
2025-05-28 18:14:07,488 INFO    MainThread:3453794 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-05-28 18:14:07,880 INFO    MainThread:3453794 [wandb_init.py:init():995] starting run threads in backend
2025-05-28 18:14:07,935 INFO    MainThread:3453794 [wandb_run.py:_console_start():2377] atexit reg
2025-05-28 18:14:07,935 INFO    MainThread:3453794 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-05-28 18:14:07,935 INFO    MainThread:3453794 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-05-28 18:14:07,935 INFO    MainThread:3453794 [wandb_run.py:_redirect():2317] Redirects installed.
2025-05-28 18:14:07,935 INFO    MainThread:3453794 [wandb_init.py:init():1037] run started, returning control to user process
2025-05-28 18:14:43,120 WARNING MsgRouterThr:3453794 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-05-28 18:14:43,126 INFO    MsgRouterThr:3453794 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
2025-05-28 18:14:43,302 INFO    MainThread:3453794 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-05-28 18:14:43,302 INFO    MainThread:3453794 [wandb_init.py:_pause_backend():564] pausing backend
2025-05-28 18:14:47,587 INFO    MainThread:3453794 [wandb_init.py:_resume_backend():569] resuming backend
2025-05-28 18:14:47,771 INFO    MainThread:3453794 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250528_181447-hmnxozfh/logs/debug.log
2025-05-28 18:14:47,771 INFO    MainThread:3453794 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250528_181447-hmnxozfh/logs/debug-internal.log
2025-05-28 18:14:47,771 INFO    MainThread:3453794 [wandb_init.py:init():761] calling init triggers
2025-05-28 18:14:47,771 INFO    MainThread:3453794 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'target_digit': 3, 'bag_size': 10, 'num_epochs': 5, 'learning_rate': 0.001, 'pooling_type': 'attention', '_wandb': {}}
2025-05-28 18:14:47,771 INFO    MainThread:3453794 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-05-28 18:14:47,771 ERROR   MainThread:3453794 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-28 18:14:48,314 INFO    MainThread:3453794 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-05-28 18:14:48,314 INFO    MainThread:3453794 [wandb_init.py:_pause_backend():564] pausing backend
