2025-02-27 09:26:06,115 INFO    MainThread:287533 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-27 09:26:06,116 INFO    MainThread:287533 [wandb_setup.py:_flush():67] Configure stats pid to 287533
2025-02-27 09:26:06,116 INFO    MainThread:287533 [wandb_setup.py:_flush():67] Loading settings from /home/javitrucas/.config/wandb/settings
2025-02-27 09:26:06,116 INFO    MainThread:287533 [wandb_setup.py:_flush():67] Loading settings from /home/javitrucas/TFG/wandb/settings
2025-02-27 09:26:06,116 INFO    MainThread:287533 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-27 09:26:06,116 INFO    MainThread:287533 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/wandb/run-20250227_092606-tc6i33zd/logs/debug.log
2025-02-27 09:26:06,116 INFO    MainThread:287533 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/wandb/run-20250227_092606-tc6i33zd/logs/debug-internal.log
2025-02-27 09:26:06,116 INFO    MainThread:287533 [wandb_init.py:init():761] calling init triggers
2025-02-27 09:26:06,116 INFO    MainThread:287533 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'dataset_name': 'rsna-features_resnet18', 'num_epochs': 10, 'learning_rate': 0.001, 'batch_size': 1, 'val_prop': 0.2, 'seed': 42, 'use_inst_distances': False, 'adj_mat_mode': 'relative', '_wandb': {}}
2025-02-27 09:26:06,117 INFO    MainThread:287533 [wandb_init.py:init():784] starting backend
2025-02-27 09:26:06,117 INFO    MainThread:287533 [wandb_init.py:init():788] sending inform_init request
2025-02-27 09:26:06,121 INFO    MainThread:287533 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-02-27 09:26:06,121 INFO    MainThread:287533 [wandb_init.py:init():803] backend started and connected
2025-02-27 09:26:06,124 INFO    MainThread:287533 [wandb_init.py:init():896] updated telemetry
2025-02-27 09:26:06,134 INFO    MainThread:287533 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-02-27 09:26:06,549 INFO    MainThread:287533 [wandb_init.py:init():995] starting run threads in backend
2025-02-27 09:26:06,694 INFO    MainThread:287533 [wandb_run.py:_console_start():2377] atexit reg
2025-02-27 09:26:06,695 INFO    MainThread:287533 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-02-27 09:26:06,696 INFO    MainThread:287533 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-02-27 09:26:06,696 INFO    MainThread:287533 [wandb_run.py:_redirect():2317] Redirects installed.
2025-02-27 09:26:06,699 INFO    MainThread:287533 [wandb_init.py:init():1037] run started, returning control to user process
2025-02-27 09:26:10,383 WARNING MsgRouterThr:287533 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-02-27 09:26:10,385 INFO    MsgRouterThr:287533 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
