2025-03-03 20:09:17,080 INFO    MainThread:557936 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-03 20:09:17,080 INFO    MainThread:557936 [wandb_setup.py:_flush():67] Configure stats pid to 557936
2025-03-03 20:09:17,080 INFO    MainThread:557936 [wandb_setup.py:_flush():67] Loading settings from /home/javitrucas/.config/wandb/settings
2025-03-03 20:09:17,080 INFO    MainThread:557936 [wandb_setup.py:_flush():67] Loading settings from /home/javitrucas/TFG/wandb/settings
2025-03-03 20:09:17,080 INFO    MainThread:557936 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-03 20:09:17,080 INFO    MainThread:557936 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/wandb/run-20250303_200917-3q5bz1el/logs/debug.log
2025-03-03 20:09:17,080 INFO    MainThread:557936 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/wandb/run-20250303_200917-3q5bz1el/logs/debug-internal.log
2025-03-03 20:09:17,080 INFO    MainThread:557936 [wandb_init.py:init():761] calling init triggers
2025-03-03 20:09:17,081 INFO    MainThread:557936 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'dataset_name': 'rsna-features_resnet18', 'num_epochs': 10, 'learning_rate': 0.001, 'batch_size': 1, 'val_prop': 0.2, 'seed': 42, 'use_inst_distances': False, 'adj_mat_mode': 'relative', 'weight_decay': 0.0001, 'dropout_prob': 0.5, 'early_stopping_patience': 5, '_wandb': {}}
2025-03-03 20:09:17,081 INFO    MainThread:557936 [wandb_init.py:init():784] starting backend
2025-03-03 20:09:17,081 INFO    MainThread:557936 [wandb_init.py:init():788] sending inform_init request
2025-03-03 20:09:17,085 INFO    MainThread:557936 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-03 20:09:17,085 INFO    MainThread:557936 [wandb_init.py:init():803] backend started and connected
2025-03-03 20:09:17,088 INFO    MainThread:557936 [wandb_init.py:init():896] updated telemetry
2025-03-03 20:09:17,097 INFO    MainThread:557936 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-03 20:09:17,472 INFO    MainThread:557936 [wandb_init.py:init():995] starting run threads in backend
2025-03-03 20:09:17,617 INFO    MainThread:557936 [wandb_run.py:_console_start():2377] atexit reg
2025-03-03 20:09:17,618 INFO    MainThread:557936 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-03 20:09:17,618 INFO    MainThread:557936 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-03 20:09:17,618 INFO    MainThread:557936 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-03 20:09:17,621 INFO    MainThread:557936 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-03 20:09:30,364 WARNING MsgRouterThr:557936 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-03 20:09:30,366 INFO    MsgRouterThr:557936 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
